#!/bin/bash

conda activate dinov2_3

#Compute
#python dino_test_on_gabors_different_area_contour_plot.py
#python dino_test_on_gabors_different_L_b_contour_plot.py
#python dino_test_on_gabors_different_rho_contour_plot.py
#python dino_test_on_gabors_different_rho_contour_plot_RG.py
#python dino_test_on_gabors_different_rho_contour_plot_YV.py

#python dinov2_test_on_gabors_different_area_contour_plot.py
#python dinov2_test_on_gabors_different_L_b_contour_plot.py
#python dinov2_test_on_gabors_different_rho_contour_plot.py
#python dinov2_test_on_gabors_different_rho_contour_plot_RG.py
#python dinov2_test_on_gabors_different_rho_contour_plot_YV.py

#python lpips_test_on_gabors_different_area_contour_plot.py
#python lpips_test_on_gabors_different_L_b_contour_plot.py
#python lpips_test_on_gabors_different_rho_contour_plot.py
#python lpips_test_on_gabors_different_rho_contour_plot_RG.py
#python lpips_test_on_gabors_different_rho_contour_plot_YV.py

#python stlpips_test_on_gabors_different_area_contour_plot.py
#python stlpips_test_on_gabors_different_L_b_contour_plot.py
#python stlpips_test_on_gabors_different_rho_contour_plot.py
#python stlpips_test_on_gabors_different_rho_contour_plot_RG.py
#python stlpips_test_on_gabors_different_rho_contour_plot_YV.py

#python openclip_test_on_gabors_different_area_contour_plot.py
#python openclip_test_on_gabors_different_L_b_contour_plot.py
#python openclip_test_on_gabors_different_rho_contour_plot.py
#python openclip_test_on_gabors_different_rho_contour_plot_RG.py
#python openclip_test_on_gabors_different_rho_contour_plot_YV.py
#
#python mae_test_on_gabors_different_area_contour_plot.py
#python mae_test_on_gabors_different_L_b_contour_plot.py
#python mae_test_on_gabors_different_rho_contour_plot.py
#python mae_test_on_gabors_different_rho_contour_plot_RG.py
#python mae_test_on_gabors_different_rho_contour_plot_YV.py

#Plot
#python plot_dino_feature_similarity_different_area_contour.py
#python plot_dino_feature_similarity_different_L_b_contour.py
#python plot_dino_feature_similarity_different_rho_contour.py
#python plot_dino_feature_similarity_different_rho_contour_RG.py
#python plot_dino_feature_similarity_different_rho_contour_YV.py

#python plot_dinov2_feature_similarity_different_area_contour.py
#python plot_dinov2_feature_similarity_different_L_b_contour.py
#python plot_dinov2_feature_similarity_different_rho_contour.py
#python plot_dinov2_feature_similarity_different_rho_contour_RG.py
#python plot_dinov2_feature_similarity_different_rho_contour_YV.py

#python plot_lpips_feature_similarity_different_area_contour.py
#python plot_lpips_feature_similarity_different_L_b_contour.py
#python plot_lpips_feature_similarity_different_rho_contour.py
#python plot_lpips_feature_similarity_different_rho_contour_RG.py
#python plot_lpips_feature_similarity_different_rho_contour_YV.py

python vae_test_on_gabors_different_area_contour_plot.py
python vae_test_on_gabors_different_L_b_contour_plot.py
python vae_test_on_gabors_different_rho_contour_plot.py
python vae_test_on_gabors_different_rho_contour_plot_RG.py
python vae_test_on_gabors_different_rho_contour_plot_YV.py
