#!/bin/bash

conda activate dinov2_3

#python dino_test_on_band_lim_noise_different_rho_band_contour_plot.py
python dinov2_test_on_band_lim_noise_different_rho_band_contour_plot.py
python lpips_test_on_band_lim_noise_different_rho_band_contour_plot.py
python openclip_test_on_band_lim_noise_different_rho_band_contour_plot.py
python mae_test_on_band_lim_noise_different_rho_band_contour_plot.py
python stlpips_test_on_band_lim_noise_different_rho_band_contour_plot.py
python baseline_test_on_band_lim_noise_different_rho_band_contour_plot.py